
import { DesignResource, Banner, Category, User } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'destaques', name: 'Destaques', slug: 'destaques' },
  { id: 'cultos', name: 'Cultos', slug: 'cultos' },
  { id: 'flyers', name: 'Flyers', slug: 'flyers' },
  { id: 'posts', name: 'Posts', slug: 'posts' },
  { id: 'datas', name: 'Datas Comemorativas', slug: 'datas-comemorativas' },
  { id: 'banners', name: 'Banners', slug: 'banners' },
  { id: 'assets', name: 'Assets', slug: 'assets' },
  { id: 'eb', name: 'Escola Bíblica', slug: 'escola-biblica' },
  { id: 'videos', name: 'Vídeos/Motion', slug: 'videos' }
];

export const MOCK_BANNERS: Banner[] = [
  {
    id: '1',
    title: 'Semana da Páscoa',
    subtitle: 'Pacote completo de artes para a semana santa. Stories, Feed e Telão.',
    image: 'https://images.unsplash.com/photo-1544427920-c49ccfb85579?q=80&w=2200&auto=format&fit=crop',
    cta: 'Ver Coleção',
    category: 'Datas Comemorativas',
    order: 1
  },
  {
    id: '2',
    title: 'Série Identidade',
    subtitle: 'Artes conceituais para séries de mensagens sobre identidade em Cristo.',
    image: 'https://images.unsplash.com/photo-1504052434569-70ad5836ab65?q=80&w=2200&auto=format&fit=crop',
    cta: 'Baixar Agora',
    category: 'Cultos',
    order: 2
  },
  {
    id: '3',
    title: 'Conferência Jovem 2024',
    subtitle: 'Energia e modernidade para o evento da sua juventude.',
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=2200&auto=format&fit=crop',
    cta: 'Explorar',
    category: 'Flyers',
    order: 3
  }
];

// Helper to generate dates relative to now
const daysAgo = (days: number) => new Date(Date.now() - days * 86400000).toISOString();

export const MOCK_RESOURCES: DesignResource[] = [
  // --- PAGINA 1 (Destaques / Recentes) ---
  {
    id: '1',
    title: 'Culto de Santa Ceia - Minimalista',
    categories: ['Cultos', 'Flyers'],
    searchTerms: 'ceia, pão, vinho, comunhão',
    imageUrl: 'https://images.unsplash.com/photo-1621360841013-c768371e93cf?q=80&w=600&auto=format&fit=crop',
    downloads: 1240,
    author: 'Kadosh Team',
    premium: false,
    tags: ['ceia', 'domingo', 'vermelho'],
    format: 'PSD',
    orientation: 'Portrait',
    canvaAvailable: true,
    canvaUrl: 'https://canva.com',
    fileSize: '45 MB',
    resolution: '300 DPI',
    dimensions: '1080x1350px',
    createdAt: daysAgo(1)
  },
  {
    id: '2',
    title: 'Worship Night - Atmosfera',
    categories: ['Flyers', 'Cultos'],
    searchTerms: 'louvor, adoração, música, jovem',
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=600&auto=format&fit=crop',
    downloads: 850,
    author: 'Hudson Soares',
    premium: true,
    tags: ['worship', 'jovens', 'moderno'],
    format: 'PSD',
    orientation: 'Portrait',
    fileSize: '120 MB',
    createdAt: daysAgo(2)
  },
  {
    id: '3',
    title: 'Versículo do Dia - Natureza',
    categories: ['Posts', 'Assets'],
    imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?q=80&w=600&auto=format&fit=crop',
    downloads: 432,
    author: 'Kadosh Team',
    premium: false,
    tags: ['instagram', 'feed', 'biblia'],
    format: 'PNG',
    orientation: 'Square',
    fileSize: '5 MB',
    createdAt: daysAgo(3)
  },
  {
    id: '4',
    title: 'Acampamento de Jovens',
    categories: ['Banners', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?q=80&w=600&auto=format&fit=crop',
    downloads: 2100,
    author: 'Hudson Soares',
    premium: true,
    tags: ['retiro', 'acampamento', 'fogueira'],
    format: 'PSD',
    orientation: 'Landscape',
    fileSize: '200 MB',
    createdAt: daysAgo(4)
  },
  {
    id: '5',
    title: 'Dia das Mães - Floral',
    categories: ['Datas Comemorativas', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1490750967868-58cb75069ed6?q=80&w=600&auto=format&fit=crop',
    downloads: 300,
    author: 'Kadosh Team',
    premium: true,
    tags: ['mães', 'mulheres', 'flores'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(5)
  },
  {
    id: '6',
    title: 'Texture Pack - Grunge',
    categories: ['Assets'],
    imageUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop',
    downloads: 150,
    author: 'Design Pro',
    premium: false,
    tags: ['textura', 'overlay', 'background'],
    format: 'JPG',
    orientation: 'Landscape',
    fileSize: '80 MB',
    createdAt: daysAgo(6)
  },
  {
    id: '7',
    title: 'Série: O Livro de João',
    categories: ['Cultos', 'Banners'],
    imageUrl: 'https://images.unsplash.com/photo-1507434965515-61970f2bd7c6?q=80&w=600&auto=format&fit=crop',
    downloads: 520,
    author: 'Hudson Soares',
    premium: true,
    tags: ['biblia', 'série', 'pregação'],
    format: 'PSD',
    orientation: 'Landscape',
    createdAt: daysAgo(7)
  },
  {
    id: '8',
    title: 'Culto da Família',
    categories: ['Cultos', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?q=80&w=600&auto=format&fit=crop',
    downloads: 890,
    author: 'Kadosh Team',
    premium: false,
    tags: ['família', 'domingo', 'casa'],
    format: 'CANVA',
    canvaAvailable: true,
    canvaUrl: 'https://canva.com',
    orientation: 'Portrait',
    createdAt: daysAgo(8)
  },
  {
    id: '9',
    title: 'Vigília de Oração',
    categories: ['Flyers', 'Cultos'],
    imageUrl: 'https://images.unsplash.com/photo-1495615080073-6b89c9839ce0?q=80&w=600&auto=format&fit=crop',
    downloads: 340,
    author: 'Design Pro',
    premium: true,
    tags: ['oração', 'fogo', 'madrugada'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(9)
  },
  {
    id: '10',
    title: 'Social Media Kit - Igreja Local',
    categories: ['Posts', 'Assets'],
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=600&auto=format&fit=crop',
    downloads: 1500,
    author: 'Kadosh Team',
    premium: true,
    tags: ['social media', 'instagram', 'kit'],
    format: 'PSD',
    orientation: 'Square',
    createdAt: daysAgo(10)
  },
  {
    id: '11',
    title: 'Background Abstrato Neon',
    categories: ['Assets', 'Vídeos/Motion'],
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop',
    downloads: 200,
    author: 'Kadosh Team',
    premium: false,
    tags: ['background', 'neon', 'led'],
    format: 'JPG',
    orientation: 'Landscape',
    createdAt: daysAgo(11)
  },
  {
    id: '12',
    title: 'EBD - Escola Bíblica',
    categories: ['Escola Bíblica', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?q=80&w=600&auto=format&fit=crop',
    downloads: 600,
    author: 'Hudson Soares',
    premium: true,
    tags: ['ebd', 'ensino', 'domingo'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(12)
  },
  // --- PAGINA 2 ---
  {
    id: '13',
    title: 'Culto de Missões',
    categories: ['Cultos', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1526976668912-1a811878dd37?q=80&w=600&auto=format&fit=crop',
    downloads: 410,
    author: 'Kadosh Team',
    premium: false,
    tags: ['missões', 'mundo', 'ide'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(13)
  },
  {
    id: '14',
    title: 'Natal - O Nascimento',
    categories: ['Datas Comemorativas', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1576692139065-d75620436d6a?q=80&w=600&auto=format&fit=crop',
    downloads: 2300,
    author: 'Design Pro',
    premium: true,
    tags: ['natal', 'jesus', 'dezembro'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(14)
  },
  {
    id: '15',
    title: 'Ano Novo - Virada',
    categories: ['Datas Comemorativas', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?q=80&w=600&auto=format&fit=crop',
    downloads: 1800,
    author: 'Hudson Soares',
    premium: true,
    tags: ['anonovo', 'réveillon', 'festa'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(15)
  },
  {
    id: '16',
    title: 'Conferência de Mulheres',
    categories: ['Flyers', 'Cultos'],
    imageUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?q=80&w=600&auto=format&fit=crop',
    downloads: 950,
    author: 'Kadosh Team',
    premium: true,
    tags: ['mulheres', 'rosa', 'conferência'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(16)
  },
  {
    id: '17',
    title: 'Batismo nas Águas',
    categories: ['Cultos', 'Posts'],
    imageUrl: 'https://images.unsplash.com/photo-1500310237930-58c0c4516301?q=80&w=600&auto=format&fit=crop',
    downloads: 720,
    author: 'Kadosh Team',
    premium: false,
    tags: ['batismo', 'água', 'renascimento'],
    format: 'CANVA',
    canvaAvailable: true,
    canvaUrl: 'https://canva.com',
    orientation: 'Square',
    createdAt: daysAgo(17)
  },
  {
    id: '18',
    title: 'Série: Apocalipse',
    categories: ['Cultos', 'Banners'],
    imageUrl: 'https://images.unsplash.com/photo-1628519592419-7892b024446f?q=80&w=600&auto=format&fit=crop',
    downloads: 1100,
    author: 'Hudson Soares',
    premium: true,
    tags: ['fim dos tempos', 'fogo', 'série'],
    format: 'PSD',
    orientation: 'Landscape',
    createdAt: daysAgo(18)
  },
  {
    id: '19',
    title: 'Dia dos Pais',
    categories: ['Datas Comemorativas', 'Posts'],
    imageUrl: 'https://images.unsplash.com/photo-1596541538356-07a82c638210?q=80&w=600&auto=format&fit=crop',
    downloads: 400,
    author: 'Design Pro',
    premium: false,
    tags: ['pais', 'homens', 'família'],
    format: 'PSD',
    orientation: 'Square',
    createdAt: daysAgo(19)
  },
  {
    id: '20',
    title: 'Motion Background - Clouds',
    categories: ['Vídeos/Motion', 'Assets'],
    imageUrl: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?q=80&w=600&auto=format&fit=crop',
    downloads: 180,
    author: 'Kadosh Team',
    premium: true,
    tags: ['loop', 'céu', 'nuvens'],
    format: 'JPG',
    orientation: 'Landscape',
    createdAt: daysAgo(20)
  },
  {
    id: '21',
    title: 'Culto de Oração',
    categories: ['Cultos'],
    imageUrl: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?q=80&w=600&auto=format&fit=crop',
    downloads: 300,
    author: 'Kadosh Team',
    premium: false,
    tags: ['oração', 'joelhos', 'intercessão'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(21)
  },
  {
    id: '22',
    title: 'Flyer Impacto Evangelístico',
    categories: ['Flyers', 'Missões'],
    imageUrl: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?q=80&w=600&auto=format&fit=crop',
    downloads: 250,
    author: 'Hudson Soares',
    premium: true,
    tags: ['rua', 'evangelismo', 'urbano'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(22)
  },
  {
    id: '23',
    title: 'Fonte Manuscrita - Holy',
    categories: ['Assets'],
    imageUrl: 'https://images.unsplash.com/photo-1560416313-414b33c856a9?q=80&w=600&auto=format&fit=crop',
    downloads: 600,
    author: 'Design Pro',
    premium: false,
    tags: ['fonte', 'tipografia', 'asset'],
    format: 'VETOR',
    orientation: 'Landscape',
    createdAt: daysAgo(23)
  },
  {
    id: '24',
    title: 'Dia do Pastor',
    categories: ['Datas Comemorativas', 'Posts'],
    imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=600&auto=format&fit=crop',
    downloads: 120,
    author: 'Kadosh Team',
    premium: true,
    tags: ['pastor', 'liderança', 'homenagem'],
    format: 'PSD',
    orientation: 'Square',
    createdAt: daysAgo(24)
  },
  // --- PAGINA 3 ---
  {
    id: '25',
    title: 'Congresso de Homens',
    categories: ['Flyers', 'Cultos'],
    imageUrl: 'https://images.unsplash.com/photo-1503443207922-dff7d543fd0e?q=80&w=600&auto=format&fit=crop',
    downloads: 480,
    author: 'Hudson Soares',
    premium: true,
    tags: ['homens', 'masculino', 'força'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(25)
  },
  {
    id: '26',
    title: 'Setembro Amarelo',
    categories: ['Datas Comemorativas', 'Posts'],
    imageUrl: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?q=80&w=600&auto=format&fit=crop',
    downloads: 800,
    author: 'Kadosh Team',
    premium: false,
    tags: ['vida', 'prevenção', 'amarelo'],
    format: 'CANVA',
    canvaAvailable: true,
    canvaUrl: 'https://canva.com',
    orientation: 'Square',
    createdAt: daysAgo(26)
  },
  {
    id: '27',
    title: 'Outubro Rosa',
    categories: ['Datas Comemorativas', 'Posts'],
    imageUrl: 'https://images.unsplash.com/photo-1551884170-09fb70a3a2ed?q=80&w=600&auto=format&fit=crop',
    downloads: 810,
    author: 'Kadosh Team',
    premium: false,
    tags: ['mulher', 'prevenção', 'rosa'],
    format: 'CANVA',
    canvaAvailable: true,
    canvaUrl: 'https://canva.com',
    orientation: 'Square',
    createdAt: daysAgo(27)
  },
  {
    id: '28',
    title: 'Série: Salmos',
    categories: ['Cultos', 'Banners'],
    imageUrl: 'https://images.unsplash.com/photo-1507692049790-de58293a4697?q=80&w=600&auto=format&fit=crop',
    downloads: 650,
    author: 'Hudson Soares',
    premium: true,
    tags: ['salmos', 'natureza', 'bíblia'],
    format: 'PSD',
    orientation: 'Landscape',
    createdAt: daysAgo(28)
  },
  {
    id: '29',
    title: 'Culto de Primícias',
    categories: ['Cultos', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1620783770629-122b7f187703?q=80&w=600&auto=format&fit=crop',
    downloads: 300,
    author: 'Design Pro',
    premium: true,
    tags: ['oferta', 'frutos', 'trigo'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(29)
  },
  {
    id: '30',
    title: 'Overlay Luz Divina',
    categories: ['Assets'],
    imageUrl: 'https://images.unsplash.com/photo-1513569771920-c9e1d31714b0?q=80&w=600&auto=format&fit=crop',
    downloads: 250,
    author: 'Kadosh Team',
    premium: false,
    tags: ['luz', 'overlay', 'efeito'],
    format: 'PNG',
    orientation: 'Landscape',
    createdAt: daysAgo(30)
  },
  {
    id: '31',
    title: 'Culto da Virada',
    categories: ['Datas Comemorativas', 'Cultos'],
    imageUrl: 'https://images.unsplash.com/photo-1492546662074-e22f7eb2694d?q=80&w=600&auto=format&fit=crop',
    downloads: 1400,
    author: 'Hudson Soares',
    premium: true,
    tags: ['fim de ano', 'virada', '2025'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(31)
  },
  {
    id: '32',
    title: 'Cardápio Cantina',
    categories: ['Flyers', 'Assets'],
    imageUrl: 'https://images.unsplash.com/photo-1554998171-7e508fda0d49?q=80&w=600&auto=format&fit=crop',
    downloads: 90,
    author: 'Kadosh Team',
    premium: false,
    tags: ['comida', 'cantina', 'preços'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(32)
  },
  {
    id: '33',
    title: 'Avisos da Semana',
    categories: ['Posts', 'Assets'],
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=600&auto=format&fit=crop',
    downloads: 1100,
    author: 'Kadosh Team',
    premium: false,
    tags: ['avisos', 'agenda', 'informação'],
    format: 'CANVA',
    canvaAvailable: true,
    canvaUrl: 'https://canva.com',
    orientation: 'Square',
    createdAt: daysAgo(33)
  },
  {
    id: '34',
    title: 'Mockup Camiseta Ministry',
    categories: ['Assets'],
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=600&auto=format&fit=crop',
    downloads: 400,
    author: 'Design Pro',
    premium: true,
    tags: ['mockup', 'camiseta', 'estampa'],
    format: 'PSD',
    orientation: 'Square',
    createdAt: daysAgo(34)
  },
  {
    id: '35',
    title: 'Capa YouTube - Live',
    categories: ['Banners', 'Videos'],
    imageUrl: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?q=80&w=600&auto=format&fit=crop',
    downloads: 600,
    author: 'Hudson Soares',
    premium: true,
    tags: ['youtube', 'thumbnail', 'live'],
    format: 'PSD',
    orientation: 'Landscape',
    createdAt: daysAgo(35)
  },
  {
    id: '36',
    title: 'Culto das Crianças',
    categories: ['Cultos', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1472162072942-cd5147eb3902?q=80&w=600&auto=format&fit=crop',
    downloads: 330,
    author: 'Kadosh Team',
    premium: false,
    tags: ['kids', 'crianças', 'infantil'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(36)
  },
  // --- PAGINA 4 ---
  {
    id: '37',
    title: 'Série: Heróis da Fé',
    categories: ['Cultos', 'Banners'],
    imageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=600&auto=format&fit=crop',
    downloads: 700,
    author: 'Hudson Soares',
    premium: true,
    tags: ['fé', 'hebreus', 'história'],
    format: 'PSD',
    orientation: 'Landscape',
    createdAt: daysAgo(37)
  },
  {
    id: '38',
    title: 'Convite Especial',
    categories: ['Convites', 'Posts'],
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=600&auto=format&fit=crop',
    downloads: 200,
    author: 'Kadosh Team',
    premium: false,
    tags: ['convite', 'elegante', 'simples'],
    format: 'CANVA',
    canvaAvailable: true,
    canvaUrl: 'https://canva.com',
    orientation: 'Portrait',
    createdAt: daysAgo(38)
  },
  {
    id: '39',
    title: 'Background Glitch',
    categories: ['Assets'],
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=600&auto=format&fit=crop',
    downloads: 150,
    author: 'Design Pro',
    premium: true,
    tags: ['glitch', 'tecnologia', 'ruído'],
    format: 'JPG',
    orientation: 'Landscape',
    createdAt: daysAgo(39)
  },
  {
    id: '40',
    title: 'Páscoa - Ele Vive',
    categories: ['Datas Comemorativas', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1522441815192-d9f04eb0615c?q=80&w=600&auto=format&fit=crop',
    downloads: 2800,
    author: 'Hudson Soares',
    premium: true,
    tags: ['páscoa', 'ressurreição', 'cruz'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(40)
  },
  {
    id: '41',
    title: 'Louvorzão Acústico',
    categories: ['Flyers', 'Cultos'],
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=600&auto=format&fit=crop',
    downloads: 360,
    author: 'Kadosh Team',
    premium: false,
    tags: ['violão', 'acústico', 'música'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(41)
  },
  {
    id: '42',
    title: 'Textura Papel Rasgado',
    categories: ['Assets'],
    imageUrl: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?q=80&w=600&auto=format&fit=crop',
    downloads: 500,
    author: 'Design Pro',
    premium: true,
    tags: ['papel', 'rasgado', 'colagem'],
    format: 'PNG',
    orientation: 'Square',
    createdAt: daysAgo(42)
  },
  {
    id: '43',
    title: 'Série: Provérbios',
    categories: ['Cultos', 'Banners'],
    imageUrl: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=600&auto=format&fit=crop',
    downloads: 440,
    author: 'Hudson Soares',
    premium: true,
    tags: ['sabedoria', 'livro', 'antigo'],
    format: 'PSD',
    orientation: 'Landscape',
    createdAt: daysAgo(43)
  },
  {
    id: '44',
    title: 'Welcome - Telão',
    categories: ['Banners', 'Assets'],
    imageUrl: 'https://images.unsplash.com/photo-1505236858219-8359eb29e329?q=80&w=600&auto=format&fit=crop',
    downloads: 300,
    author: 'Kadosh Team',
    premium: false,
    tags: ['bem-vindo', 'telão', 'projeção'],
    format: 'JPG',
    orientation: 'Landscape',
    createdAt: daysAgo(44)
  },
  {
    id: '45',
    title: 'Dia da Bíblia',
    categories: ['Datas Comemorativas', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1491396023581-4344e51f4575?q=80&w=600&auto=format&fit=crop',
    downloads: 150,
    author: 'Kadosh Team',
    premium: false,
    tags: ['bíblia', 'palavra', 'escritura'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(45)
  },
  {
    id: '46',
    title: 'Culto da Vitória',
    categories: ['Cultos', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1565056221147-36c53d508931?q=80&w=600&auto=format&fit=crop',
    downloads: 420,
    author: 'Hudson Soares',
    premium: true,
    tags: ['vitória', 'conquista', 'festa'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(46)
  },
  {
    id: '47',
    title: 'Estudo de Célula',
    categories: ['Flyers', 'Posts'],
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=600&auto=format&fit=crop',
    downloads: 610,
    author: 'Kadosh Team',
    premium: false,
    tags: ['célula', 'grupo', 'comunhão'],
    format: 'CANVA',
    canvaAvailable: true,
    canvaUrl: 'https://canva.com',
    orientation: 'Square',
    createdAt: daysAgo(47)
  },
  {
    id: '48',
    title: 'Série: Neemias',
    categories: ['Cultos', 'Banners'],
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=600&auto=format&fit=crop',
    downloads: 500,
    author: 'Hudson Soares',
    premium: true,
    tags: ['reconstrução', 'muros', 'liderança'],
    format: 'PSD',
    orientation: 'Landscape',
    createdAt: daysAgo(48)
  },
  {
    id: '49',
    title: 'Aniversário da Igreja',
    categories: ['Datas Comemorativas', 'Flyers'],
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-e8d4aa97edf9?q=80&w=600&auto=format&fit=crop',
    downloads: 900,
    author: 'Design Pro',
    premium: true,
    tags: ['aniversário', 'festa', 'celebração'],
    format: 'PSD',
    orientation: 'Portrait',
    createdAt: daysAgo(49)
  },
  {
    id: '50',
    title: 'Background Partículas Douradas',
    categories: ['Assets', 'Vídeos/Motion'],
    imageUrl: 'https://images.unsplash.com/photo-1516055108669-14a51eb0d588?q=80&w=600&auto=format&fit=crop',
    downloads: 300,
    author: 'Kadosh Team',
    premium: true,
    tags: ['partículas', 'ouro', 'brilho'],
    format: 'JPG',
    orientation: 'Landscape',
    createdAt: daysAgo(50)
  }
];

export const MOCK_USERS: User[] = [
  {
    id: 'admin-1',
    name: 'Admin Kadosh',
    email: 'admin@kadosh.com',
    role: 'admin',
    plan: 'premium_annual',
    quotaUsed: 0,
    quotaTotal: 9999,
    renewalDate: 'Vitalício',
    subscriptionExpiry: null,
    lastQuotaReset: new Date().toISOString(),
    favorites: [],
    downloadsHistory: [],
    autoRenew: true
  },
  {
    id: 'member-1',
    name: 'Membro Teste',
    email: 'membro@teste.com',
    role: 'member',
    plan: 'free',
    quotaUsed: 0,
    quotaTotal: 1,
    renewalDate: 'N/A',
    subscriptionExpiry: null,
    lastQuotaReset: new Date().toISOString(),
    favorites: [],
    downloadsHistory: [],
    autoRenew: false
  },
  {
    id: 'vip-1',
    name: 'Membro VIP',
    email: 'vip@teste.com',
    role: 'member',
    plan: 'ministry',
    quotaUsed: 2,
    quotaTotal: 7,
    renewalDate: '25/12/2024',
    subscriptionExpiry: Date.now() + 10000000,
    lastQuotaReset: new Date().toISOString(),
    favorites: ['2', '4'],
    downloadsHistory: [],
    autoRenew: true
  }
];
